services:
  web:    
    image: chioffor/app:latest
    container_name: main
    ports: 
      - "8000:8000"    
    command: php artisan serve --host=0.0.0.0
    
    depends_on:
      - db
    volumes:
      - .:/app       

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: app
      MYSQL_USER: username
      MYSQL_PASSWORD: password

