services:
  web:
    image: chioffor/app
    ports: 
      - "8000:8000"    
    entrypoint: ["bash", "migrate.sh"]
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password